name: Trigger auto deployment for container-app-oldiruvtcgsvg

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '//**'
    - '.github/workflows/container-app-oldiruvtcgsvg-AutoDeployTrigger-20d15689-0561-4b21-bd1d-e07d85d3b81b.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.CONTAINERAPPOLDIRUVTCGSVG_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.CONTAINERAPPOLDIRUVTCGSVG_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.CONTAINERAPPOLDIRUVTCGSVG_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }} 
          registryUrl: 
          registryUsername: ${{ secrets.CONTAINERAPPOLDIRUVTCGSVG_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.CONTAINERAPPOLDIRUVTCGSVG_REGISTRY_PASSWORD }}
          containerAppName: container-app-oldiruvtcgsvg
          resourceGroup: djangoappspacesa00aaf1d
          imageToBuild: default/[parameters('containerAppName')]:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


